### ISSUE TITLE
ImportError: No module named docopt

### ISSUE THREAD

**Issue by yosun** [flavioribeiro/video-thumbnail-generator#11]
$pip2 install docopt
Requirement already satisfied: docopt in /usr/local/lib/python2.7/site-packages
 $ ./generator
Traceback (most recent call last):
  File "./generator", line 21, in <module>
    from docopt import docopt
ImportError: No module named docopt

**Comment by flavioribeiro** [comment]
what is the OS you are trying to build? did you try the `./build` command?
