### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by silent10** [flavioribeiro/video-thumbnail-generator#15]
# git clone git@github.com:flavioribeiro/video-thumbnail-generator.git
Cloning into 'video-thumbnail-generator'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by flavioribeiro** [comment]
try cloning from this https://github.com/flavioribeiro/video-thumbnail-generator.git
