### ISSUE TITLE
General Question: Can the VIDEO file be store on a remote bucket or server?

### ISSUE THREAD

**Issue by inglesuniversal** [flavioribeiro/video-thumbnail-generator#20]
I'm quite new to pip3 scripting... so I don't know it is possible to generate a thumbnail sprite from a remote URL or stored on a bucket (e.g. AWS / Firebase Storage).

Can it create thumbnail sprites from all of these files: MP4, MOV, MKV

Thanks for the superb script

#STAYSAFE

**Comment by mayeaux** [comment]
Did you figure it out? You would probably need to download it locally

**Comment by inglesuniversal** [comment]
I have stopped using this project for the time being. The process itself of creating thumbnails is not a must in our project. Since for educational purposes, students pretty much watch the whole video in on shot.

**Comment by flavioribeiro** [comment]
@inglesuniversal @mayeaux based on https://github.com/Zulko/moviepy/issues/204 and https://github.com/Zulko/moviepy/issues/991, [VideoClipFile](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html?highlight=videofileclip#moviepy.video.io.VideoFileClip.VideoFileClip) uses an [ffmpeg wrapper](https://github.com/Zulko/moviepy/blob/cd473ff77ca630fe53fcac74d5c63da188594240/moviepy/video/io/ffmpeg_reader.py#L13)  to read the frames. If you have your ffmpeg compiled with libcurl, the script is supposed to be able to fetch frames from remote URLs -- I didn't personally try it myself but it should work :)
