### ISSUE TITLE
Feature Request: Could you add a feature to create a VTT file like this...

### ISSUE THREAD

**Issue by inglesuniversal** [flavioribeiro/video-thumbnail-generator#21]
[VTT_THUMBNAIL_HANDLER](https://cdn.plyr.io/static/demo/thumbs/100p.vtt)

Target Player:

plyr

Thanks

**Comment by flavioribeiro** [comment]
hey @inglesuniversal this project is not being actively maintained-- I'll close this issue as dup in favor of https://github.com/flavioribeiro/video-thumbnail-generator/issues/4
